export default [
  "A Score to Settle",
  "Spider-Man: Into the Spider-Verse",
  "Between Worlds",
  "Teen Titans Go! To the Movies",
  "211",
  "Looking Glass",
  "Mandy",
  "The Humanity Bureau",
  "Mom and Dad",
  "Inconceivable",
  "Vengeance: A Love Story",
  "Arsenal",
  "Army of One",
  "USS Indianapolis: Men of Courage",
  "Snowden",
  "Dog Eat Dog",
  "The Trust",
  "Pay the Ghost",
  "The Runner",
  "Dying of the Light",
  "Left Behind",
  "Outcast",
  "Rage",
  "Joe",
  "The Frozen Ground",
  "The Croods",
  "Stolen",
  "Ghost Rider: Spirit of Vengeance",
  "Trespass",
  "Seeking Justice",
  "Drive Angry",
  "Season of the Witch",
  "The Sorceror's Apprentice",
  "Kick-Ass",
  "Astro Boy",
  "Bad Lieutenant: Port of Call New Orleans",
  "G-Force",
  "Knowing",
  "Bangkok Dangerous",
  "National Treasure: Book of Secrets",
  "Next",
  "Grindhouse",
  "Ghost Rider",
  "The Wicker Man",
  "World Trade Center",
  "The Ant Bully",
  "The Weather Man",
  "Lord of War",
  "National Treasure",
  "Matchstick Men",
  "Adaptation.",
  "Sonny",
  "Windtalkers",
  "A Christmas Carol",
  "Captain Corelli's Mandolin",
  "The Family Man",
  "Gone in Sixty Seconds",
  "Bringing Out the Dead",
  "8MM",
  "Snake Eyes",
  "City of Angels",
  "Face/Off",
  "Con Air",
  "The Rock",
  "Leaving Las Vegas",
  "Kiss of Death",
  "Trapped in Paradise",
  "It Could Happen to You",
  "Guarding Tess",
  "Deadfall",
  "Red Rock West",
  "Amos and Andrew",
  "Honeymoon in Vegas",
  "Zandalee",
  "Industrial Symphony No. 1: The Dream of the Brokenhearted",
  "Fire Birds",
  "Wild at Heart",
  "Time to Kill",
  "Never on Tuesday",
  "Vampire's Kiss",
  "Moonstruck",
  "Raising Arizona",
  "Peggy Sue Got Married",
  "The Boy in Blue",
  "Birdy",
  "The Cotton Club",
  "Racing with the Moon",
  "Rumble Fish",
  "Valley Girl",
  "Fast Times at Ridgemont High",
  "Best of Times"
]
